# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude: /package-lock\.json$
      - id: check-added-large-files
        args:
          - --maxkb=1000
      - id: check-merge-conflict

  # Secrets
  - repo: https://github.com/awslabs/git-secrets
    rev: 80230afa8c8bdeac766a0fece36f95ffaa0be778
    hooks:
      - id: git-secrets
        entry: git-secrets --scan
        files: .

  # Ansible lint
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.2.0
    hooks:
      - id: ansible-lint
        exclude: ^.pre-commit-config.yaml/
