# Select the main tasks to run. Set to true|false.
configure_homebrew: true
configure_mas: true
configure_osx: true
configure_dotfiles: true

# Select the subtasks to run. Set to true|false.
homebrew_upgrade_all_packages: true
configure_hostname: true
configure_dock: true
configure_desktop: true
configure_ohmyzsh: true
configure_ssh: true

# Configure ComputerName, HostName, and LocalHostName.
computername: MyComputer # Didn't figure out how to escape special characters <User\'s\ MBA> works but always reports change.
hostname: myhostname

# Configure macOS Dock.
enable_dock_magnification: true
dock_magnification_value: 64
dock_position: bottom
minimize_windows_into_application_icon: true
show_suggested_and_recent_applications_in_dock: true

# Configure macOS Desktop.
click_wallpaper_to_reveal_desktop: false
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# 13: Lock Screen
hot_corner_top_left: 2
hot_corner_top_right: 4
hot_corner_bottom_left: 5
hot_corner_bottom_right: 11

# Register homebrew taps.
homebrew_taps:
  - homebrew/cask-versions

# Install homebrew packages.
homebrew_packages:
  - awscli
  - aws-sam-cli
  - cfn-lint
  - gh
  - git
  - mas
  - pre-commit
  - tree
  - vim
  - wget
  - zsh

# Install homebrew casks.
homebrew_apps:
  - docker
  - dropbox
  - iterm2

# Install App Store apps.
mas_installed_apps:
  - { id: 443987910, name: 1Password v6.8.9 }
  - { id: 937984704, name: Amphetamine }

# Upgrade App Store apps.
mas_upgrade_all_apps: false

# Uninstall App Store apps.
# This is currently bugged, see https://github.com/mas-cli/mas/issues/216. To uninstall app requires
# sudo, however `sudo mas list` has no application installed.
mas_uninstalled_apps:
#  - { id: 682658836, name: GarageBand }

# Install and configure zsh and oh-my-zsh.
macos_ohmyzsh:
  default_shell: true # Set zsh as default shell?
  configure_oh_my_zsh: true # Configure oh-my-zsh after install?
  config:
    theme: robbyrussell
    case_sensitive: false
    hyphen_insensitive: false
    disable_magic_functions: false
    disable_ls_colors: false
    disable_auto_title: false
    enable_correction: false
    completion_waiting_dots: false
    disable_untracked_files_dirty: false
    custom: $ZSH/custom
    plugins: git
    profile_path: ~/.zprofile

ssh_hosts:
  - name: '*'
    options:
      AddKeysToAgent: yes
      UseKeychain: yes
      IdentityFile: ~/.ssh/id_ecdsa
  - name: my-server-name
    options:
      HostName: 192.168.1.1
      User: myuser
      IdentityFile: ~/.ssh/id_ecdsa
