---
- hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: homebrew
      when: configure_homebrew
      tags: ['homebrew']
    - role: mas
      when: configure_mas
      tags: ['mas']
    - role: osx
      when: configure_osx
      tags: ['osx']
    - role: dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
