---
- hosts: localhost

  pre_tasks:
    - name: Include configuration
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - config.yml
            - default.config.yaml
          skip: true
      tags: ['always']

  roles:
    - role: homebrew
      tags: [homebrew]
    - role: mas
      tags: [mas]
    - role: osx
      tags: [osx]
