---
macos_ohmyzsh:
  default_shell: true
  configure_oh_my_zsh: true
  config:
    theme: "robbyrussell"
    case_sensitive: false
    hyphen_insensitive: false
    disable_magic_functions: false
    disable_ls_colors: false
    disable_auto_title: false
    enable_correction: false
    completion_waiting_dots: true
    disable_untracked_files_dirty: false
    custom: "$ZSH/custom"
    plugins: "git"
