macos_ohmyzsh:
  default_shell: null
  configure_oh_my_zsh: null
  config:
    theme: null
    case_sensitive: null
    hyphen_insensitive: null
    disable_magic_functions: null
    disable_ls_colors: null
    disable_auto_title: null
    enable_correction: null
    completion_waiting_dots: null
    disable_untracked_files_dirty: null
    custom: null
    plugins: null
    profile_path: null
