- name: Include OhMyZSH config tasks
  include_tasks: oh_my_zsh.yml
  tags: [oh-my-zsh]
  when: configure_ohmyzsh

- name: Include SSH config tasks
  include_tasks: ssh_conf.yml
  tags: [ssh-config]
  when: configure_ssh
