---
- name: Setup ComputerName, HostName, and LocalHostName
  import_tasks: hostname.yml
  tags: [osx-hostname]
  when: configure_hostname

- name: Setup Dock
  import_tasks: dock.yml
  tags: [osx-dock]
  when: configure_dock

- name: Setup Desktop
  import_tasks: desktop.yml
  tags: [osx-desktop]
  when: configure_desktop
